export const HOME_SLIDER_SUCCESS = 'HOME_SLIDER_SUCCESS';
export const HOME_SLIDER_FAILURE = 'HOME_SLIDER_FAILURE';
export const HOME_SLIDER_LOAD = 'HOME_SLIDER_LOAD';
export const HOME_TOP_CATEGORIES_SUCCESS = 'HOME_TOP_CATEGORIES_SUCCESS';
export const HOME_TOP_CATEGORIES_FAILURE = 'HOME_TOP_CATEGORIES_FAILURE';
export const HOME_TOP_CATEGORIES_LOAD = 'HOME_TOP_CATEGORIES_LOAD';
export const HOME_MOST_POPULAR_PRODUCTS_SUCCESS = 'HOME_MOST_POPULAR_PRODUCTS_SUCCESS';
export const HOME_MOST_POPULAR_PRODUCTS_FAILURE = 'HOME_MOST_POPULAR_PRODUCTS_FAILURE';
export const HOME_MOST_POPULAR_PRODUCTS_LOAD = 'HOME_MOST_POPULAR_PRODUCTS_LOAD';
export const HOME_CATEGORIES_SUCCESS = 'HOME_CATEGORIES_SUCCESS';
export const HOME_CATEGORIES_FAILURE = 'HOME_CATEGORIES_FAILURE';
export const HOME_CATEGORIES_LOAD = 'HOME_CATEGORIES_LOAD';

export function loadHomeSliderData() {
    return { type: HOME_SLIDER_LOAD }
  }

export function loadTopCategoryData() {
    return { type: HOME_TOP_CATEGORIES_LOAD }
  }
  export function loadCategoryData() {
    return { type: HOME_CATEGORIES_LOAD }
  }
  export function loadMostPopularData() {
    return { type: HOME_MOST_POPULAR_PRODUCTS_LOAD }
  }